title: Ha Minh Thuan

description: ğŸ‘¾ğŸ–¥ï¸Cybersecurity (Fresher)ğŸ–¥ï¸ğŸ‘¾

address: Ho Chi Minh - Viet Nam
email: "Thuanhm.spkt@gmail.com"
phone: "0792692655"
linkedin: "https://www.linkedin.com/in/h%C3%A0-minh-thu%E1%BA%ADn-86166b170/"

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: youremail@gmail.com # Allow visitors to contact you
