title: Ha Minh Thuan

description: ğŸ‘¾ğŸ–¥ï¸Cybersecurity (Fresher)ğŸ–¥ï¸ğŸ‘¾

address: Ho Chi Minh - Viet Nam
phone: "0792692655"

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: youremail@gmail.com # Allow visitors to contact you
